### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Krystex** [Krystex/Boids#1]
- [x] Set number of boids/predators in interface
- [ ] Don't expose whole `ecs` context in systems (for better separation)
- [ ] Add ECS example in README
- [ ] Show statistics (ECS computation)
- [ ] Cleanup code a bit
